- app/assets/styles/analytics.scss
> fix title bug

- app/assets/scripts/utils/line-colors.js
- app/assets/styles/explore.scss
Switch it back to a green-red scale.
> Switch IRI gradient to green-red. Fix #106

- app/assets/scripts/views/analytics-admin-area.js
I'd set up the logic to render once data was no longer fetching.
Switching that to waiting until data was fetched seems to have fixed the problem.
> fix data loading issue

- app/assets/scripts/components/site-header.js
- app/assets/scripts/main.js
- app/assets/scripts/views/upload.js
closes https://github.com/orma/openroads-vn-analytics/issues/227
cc @olafveerman
> Add unstyled upload for RLP geometries and properties

- app/assets/scripts/components/aa-table-index.js
- app/assets/scripts/components/aa-table-vpromms.js
- app/assets/scripts/components/page-header.js
- app/assets/scripts/components/site-header.js
- app/assets/scripts/main.js
- app/assets/scripts/reducers/reducer.js
- app/assets/scripts/utils/pagination.js
- app/assets/scripts/views/assets-admin-area.js
- app/assets/scripts/views/assets-index.js
- app/assets/scripts/views/assets.js
- app/assets/scripts/views/home.js
- app/assets/styles/main.scss
- app/assets/styles/pages/_assets.scss
- app/assets/styles/pages/_explore.scss
closes https://github.com/orma/openroads-vn-analytics/issues/243
> Switch all references from Analytics to Assets

- app/assets/scripts/components/aa-table-vpromms.js
- sort asset tables in ascending order.
> sort ascending to show field data first

- app/assets/scripts/components/map-search.js
- app/assets/scripts/config/staging.js
- app/assets/scripts/redux/modules/map.js
- app/assets/scripts/redux/modules/roads.js
- app/assets/scripts/views/editor.js
Fixes #270 
Here's how it works:
> Search in the editor selects the feature for editing

- app/assets/scripts/redux/modules/osm.js
- app/assets/scripts/redux/modules/roads.js
- app/assets/scripts/redux/modules/tasks.js
- app/assets/scripts/views/tasks.js
fixes https://github.com/orma/openroads-vn-analytics/issues/310
cc @kamicut
> apply vprommid on dedupe

- app/assets/scripts/redux/modules/tasks.js
- app/assets/scripts/views/tasks.js
fixes https://github.com/orma/openroads-vn-analytics/issues/401
> explicitly say when there are no tasks instead of just error

- app/assets/scripts/redux/modules/map.js
- app/assets/scripts/views/editor.js
fixes https://github.com/orma/openroads-vn-analytics/issues/395
> propagate wayslug. fix invalid property

- app/assets/scripts/views/explore.js
- app/index.html
- package.json
- yarn.lock
fixes https://github.com/orma/openroads-vn-analytics/issues/389
> upgrade mapboxgl. use dasharray style

- app/assets/scripts/views/editor.js
> set viewport to vietnam by default

- app/assets/locales/source/en.json
- app/assets/scripts/components/map-search.js
> search admins with space

- app/assets/scripts/redux/modules/roads.js
fixes https://github.com/orma/openroads-vn-analytics/issues/376
> remove the road from the state when deleted

- .gitignore
- app/assets/scripts/views/tasks.js
- package.json
- yarn.lock
Close #429 
Close #430 
@geohacker this gets us closer but not all the way there. It would help to have your clarification in [what to do with two intersecting ways](https://github.com/orma/openroads-vn-analytics/issues/430#issuecomment-402842945).
> Calculate closest point between two linestrings for non-intersecting ways

- app/assets/scripts/redux/modules/tasks.js
> fix bug where panel shows blank post fixing a task

- app/OR_frame_notifier.js
- app/assets/scripts/views/assets-detail.js
- app/assets/scripts/views/editor.js
- package.json
- yarn.lock
Use a better notifier to talk to iD
Pr on openroads-vn-iD is needed: https://github.com/orma/openroads-vn-iD/pull/49
> User new ORFrameNotifier

- app/assets/scripts/views/tasks.js
- app/assets/styles/global/_panels.scss
Fixes #460 
- Allows user to mark a Task as `Error` or `Not an Error`.
- If user selects `Not an Error`, clicking Skip Task calls `.markAsDone()` to mark the task as done before going to the next task.
cc @geohacker @ricardomestre
> Skip task options

- app/assets/scripts/views/job.js
Remove `job` from the view state and just get from props.
cc @danielfdsilva
> dont store job in view state, get from props

- app/assets/scripts/views/explore.js
- app/assets/scripts/views/tasks.js
- app/assets/styles/components/_map.scss
Ref https://github.com/orma/openroads-vn-analytics/issues/370
> [ready] Base map improvements

- app/assets/scripts/views/editor.js
Uses new `setPosition` message to update map position in the editor when user clicks on an admin / vpromm search result.
cc @geohacker
> Fix Editor search bug

- app/assets/scripts/views/explore.js
Fixes https://github.com/orma/openroads-vn-analytics/issues/498
cc @batpad
> Explore map layers

- app/assets/scripts/components/base-search.js
> clear search dropdown after navigating to result on assets search

- app/assets/scripts/components/assets-section-row.js
- app/assets/scripts/utils/export-json.js
- app/assets/scripts/utils/section-fields.js
- app/assets/scripts/utils/sections.js
- app/assets/scripts/views/assets-detail.js
This is a WIP.
Currently, gathers all the data, gets labels and verbose values, etc. and builds a `header` with an array of the header columns and `rows` with an array of arrays of values.
@geohacker - this should be pretty easy to render wherever / however we need to now that we have the data structure in place.
> Show section details on VPRoMM asset page

- app/assets/scripts/components/map-legend.js
- app/assets/scripts/components/map-options.js
- app/assets/scripts/utils/line-colors.js
- app/assets/scripts/views/explore.js
@geohacker - this should all work - probably needs a bit of work on the styling and stop values. Can you give this a test and provide feedback? Thanks.
> add CVTS layer to Explore page

- app/assets/scripts/views/assets-detail.js
- app/assets/styles/pages/_assets.scss
Fixes https://github.com/orma/openroads-vn-analytics/issues/533.
> Asset page layout improvements

- app/assets/scripts/actions/action-creators.js
Fixes #537 
Needs https://github.com/orma/openroads-vn-api/pull/178 to be merged into the back-end first.
cc @geohacker
> use /road/ids endpoint on editor search instead of /field/ids

- app/assets/scripts/components/assets-create.js
- app/assets/scripts/redux/modules/roads.js
* catch existing roads
* validate province id
* catch invalid vpromm id
cc @batpad
> Better error handling while adding new road

- app/assets/scripts/components/map-legend.js
- app/assets/scripts/components/map-options.js
- app/assets/scripts/redux/reducer.js
- app/assets/scripts/utils/line-colors.js
- app/assets/scripts/views/explore.js
> Make CVTS part of the same tileset

- app/assets/scripts/views/assets-detail.js
Fixes https://github.com/orma/openroads-vn-analytics/issues/563
cc @batpad
> don't omit asset props

- app/assets/scripts/redux/modules/roads.js
- app/assets/scripts/views/assets-detail.js
> handle 404 of a deleted asset

- app/assets/scripts/views/upload.js
> make file input required for upload

- app/assets/scripts/redux/modules/admin-stats.js
- app/assets/scripts/views/assets-admin-area.js
> display error if province not found, fixes #587

- app/assets/scripts/views/editor.js
Fixes selecting feature when searching for VPRomm on the Editor page.
cc @geohacker
> only fire setPosition when props have changed

- app/assets/scripts/components/base-search.js
> clear search box on assets search when user navigates to vpromm / admin
